version: '3'

services:
  redis:
    image: redis:5-alpine
    #    platform: linux/amd64
    command: --port 6393
    ports:
      - "6393:6393"
    expose:
      - 6393
    restart: always

  app:
    #    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_RUNNING_IN_DOCKER=true
    depends_on:
      - redis
    command: python manage.py runserver 0.0.0.0:5020

    volumes:
      - .:/app/backend

    ports:
      - "5020:5020"
    env_file:
      - .env
    restart: always


